# Site settings
# Site settings
title: "The Milky Way in My Reach"
subtitle: "R Wang's Art Archive"
email: your-email@example.com
description: "R Wang's Art Archive"
baseurl: ""
repository: "rywang42/rywang42.github.io"
# Social media links
github_username: rywang42

github: [metadata]
repository: rywang42/rywang42.github.io
url: "https://rywang42.github.io"

header: images/logo.png

# # Formspree contact Form
# contact_form: "https://formspree.io/ctarwater@chrisanthropic.com"


# Exclude our ruby stuff
exclude: [.bundle, .vendor, .bin, starving-artist.gemspec, bin, vendor, Gemfile, Gemfile.lock, Rakefile, s3_website.yml, starving-artist-jekyll-theme-*.gem]


# Build settings
markdown: kramdown
kramdown:
  input: GFM

# theme: starving-artist-jekyll-theme

# Plugins
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jemoji
  - jekyll-include-cache
  - jekyll-redirect-from
feed:
  path: atom.xml

# Compress our Css
sass:
   style: :compressed

include: ['_pages']

permalink: /blog/:year/:title

collections:
  - galleries

#### SEO Stuff
# Google Analytics
google_universal_analytics:
google_universal_analytics_cookiedomain: auto

# Facebook Opengraph
facebook_user:
facebook_app_id:                                #enter your App ID
facebook_locale: en_US
facebook_page:                                  #the URL of your Facebook Page
facebook_image: images/author.jpg                      #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.

# Twitter Cards
twitter_user:
twitter_card: true
twitter_image: images/author.jpg                       #enter a default image (at least 200x200px) to use here for posts/pages that don't have one.
